import { useNavigate } from 'react-router-dom'

export default function TermsPage() {
  const navigate = useNavigate()

  return (
    <div className="flex-1 overflow-y-auto bg-gray-50 min-h-full">
      <div className="max-w-2xl mx-auto px-6 py-10">

        {/* Back button */}
        <button
          onClick={() => navigate(-1)}
          className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-800 mb-8 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
          Back
        </button>

        <h1 className="text-2xl font-bold text-gray-900 mb-1">Terms &amp; Conditions</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: May 2025</p>

        <div className="space-y-8 text-sm text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using EJ Newsfeed, you agree to be bound by these Terms and Conditions.
              If you do not agree, please discontinue use of the application.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">2. Description of Service</h2>
            <p>
              EJ Newsfeed is a personal news aggregation tool that connects to your Gmail account,
              extracts newsletter content, and presents it in a structured digest with AI-generated
              summaries and trend analysis. The service is provided as-is for personal use.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">3. Use of the Service</h2>
            <p className="mb-2">You agree to use EJ Newsfeed only for lawful purposes. You may not:</p>
            <ul className="list-disc list-inside space-y-1 pl-2">
              <li>Attempt to reverse engineer, decompile, or extract the source code</li>
              <li>Use the service in any way that could damage, disable, or impair it</li>
              <li>Share your access credentials with others</li>
              <li>Use the service for commercial purposes without explicit permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">4. Gmail Access</h2>
            <p>
              EJ Newsfeed requests read-only access to your Gmail account to identify and process
              newsletter emails. You grant this access voluntarily via Google OAuth. You may revoke
              this access at any time through your Google Account settings, which will prevent the
              service from processing future emails.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">5. AI-Generated Content</h2>
            <p>
              Article summaries and trend analysis are generated using AI models. While we strive
              for accuracy, AI-generated content may contain errors or omissions. EJ Newsfeed is not
              responsible for decisions made based on AI-generated summaries. Always refer to the
              original source for authoritative information.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">6. Intellectual Property</h2>
            <p>
              All content displayed in EJ Newsfeed originates from third-party newsletters and
              publications. EJ Newsfeed does not claim ownership of any newsletter content.
              Summaries generated by the service are derivative works for personal use only.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">7. Disclaimer of Warranties</h2>
            <p>
              EJ Newsfeed is provided "as is" without warranties of any kind, express or implied.
              We do not guarantee uninterrupted access, accuracy of content, or fitness for any
              particular purpose. Use of the service is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, EJ Newsfeed and its operators shall not be
              liable for any indirect, incidental, or consequential damages arising from your use
              of or inability to use the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">9. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms at any time. Continued use of the service
              after changes are posted constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-gray-900 mb-2">10. Contact</h2>
            <p>
              Questions about these Terms can be directed to{' '}
              <a href="mailto:euijjung@umich.edu" className="text-violet-600 hover:underline">
                euijjung@umich.edu
              </a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
